-- Each new term in the Fibonacci sequence is generated by adding
-- the previous two terms. By starting with 1 and 2.
-- Find the sum of all even Fibonacci that do not exceed 4 mil.

fib n a b
    | n == 0 = a
    | n == 1 = b
    | n > 1 = fib (n-1) b (a+b)

sumEvenfib max a b
    | b > max   = 0
    | even b    = b + sumEvenfib max b (a+b)
    | odd b     = sumEvenfib max b (a+b)